### ISSUE TITLE
whether the train loss converges in the training process?

### ISSUE THREAD

**Issue by liu311** [pandeydeep9/EvidentialResearch2023#3]
After Considering the loss of the correct evidence regularization term, i am confused about whether the train loss converges in the training process. i tried to run your "MainMnistExperiment" experiment, but i think that the train loss does not converge to 0 or some non-negative value.

**Comment by pandeydeep9** [comment]
The loss proposed in this work can take negative values due to the correct evidence regularization term. One minor theoretical fix to ensure that the loss is non-negative, and converges to 0 is to use the exponential of the L_cor, but I have not checked its impact empirically. For the current loss in the paper, I think the loss converged to some value. I will double-check and update you once I have time to take a closer look.

**Comment by pandeydeep9** [comment]
I ran the MNIST experiment and the model performance looks reasonable. I ran the experiments for 50 epochs. For the evidential model, as training progresses, the loss decreases and slowly starts to converge. For instance, with incorrect evidence regularization strength of 1.0, loss started from 0.44 and converged to around 0.06 in 50 epochs. I wonder if you can provide additional details of the issue?

**Comment by liu311** [comment]
Thank you for your patient reply. I may make some mistakes in reproducing your code.In my research dataset, the loss has been declining and has not been converged even in 200 epochs. Now it seems that there may be a problem in the my process of reproducing the code. Anyway, thank u again !
